date: "{{ lookup('pipe', 'date +%m%d%Y-%H%M') }}"
app_env: "prod"
appname: "sqe_module"
app_env_name: "{{ app_env }}_{{ appname }}"
wpDir: "/var/lib/jenkins/workspace/DR_SMARTQE/DEV/DEV-SQE-APP/"
infraSrcDir: "{{wpDir}}/InfraRepo"
infraDesDir: "/opt/{{appname}}"
infraScriptsdir: "{{ infraDesDir }}/InfraRepo/scripts"
BKdir: "/opt/buildBackups"
appbuildpath: "/opt/app_builds/java"
appbuildDir: "/opt/app_builds/java/{{ app_env_name }}/"
appbuildFile: "{{ appbuildDir }}/target/"
existingwarfiles: "/opt/tomcat/webapps/*.war"
RemoteServerDir: "/opt/tomcat/webapps"
RemoteServerBKDir: "/prodapps/smartqe/backups"  