# date: "{{ lookup('pipe', 'date +%m%d%Y-%H%M') }}"
# app_env: "preprod"
# appname: "eshop_module"
# app_env_name: "{{ appname }}_{{ app_env }}"
# wpDir: "/var/lib/jenkins/workspace/ESHOP/ME_ESHOP/PREPROD/PP-ESHOP-APP/"
# infraSrcDir: "{{wpDir}}/InfraRepo"
# infraDesDir: "/opt/{{appname}}"
# infraScriptsdir: "{{ infraDesDir }}/InfraRepo/scripts"
# BKdir: "/opt/app-builds/BuildBackups"
# appbuildpath: "/opt/app-builds/reactapps"
# appbuildDir: "/opt/app-builds/reactapps/{{ app_env_name }}/"
# RemoteServerDir: "/preprodapps/onehubpos/me_eshop"
# RemoteServerBKDir: "/preprodapps/onehubpos/backups"   